// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: internal/proto/forgepb/forge.proto

package forgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ForgeScheduler_SubmitTask_FullMethodName       = "/forge.ForgeScheduler/SubmitTask"
	ForgeScheduler_GetTaskStatus_FullMethodName    = "/forge.ForgeScheduler/GetTaskStatus"
	ForgeScheduler_RegisterWorker_FullMethodName   = "/forge.ForgeScheduler/RegisterWorker"
	ForgeScheduler_ReportTaskResult_FullMethodName = "/forge.ForgeScheduler/ReportTaskResult"
	ForgeScheduler_WatchTask_FullMethodName        = "/forge.ForgeScheduler/WatchTask"
	ForgeScheduler_GetClusterInfo_FullMethodName   = "/forge.ForgeScheduler/GetClusterInfo"
	ForgeScheduler_ListTasks_FullMethodName        = "/forge.ForgeScheduler/ListTasks"
	ForgeScheduler_GetDashboardData_FullMethodName = "/forge.ForgeScheduler/GetDashboardData"
)

// ForgeSchedulerClient is the client API for ForgeScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ForgeSchedulerClient interface {
	SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error)
	GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error)
	RegisterWorker(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerHeartbeat, TaskAssignment], error)
	ReportTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskResultAck, error)
	WatchTask(ctx context.Context, in *WatchTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskStatusResponse], error)
	GetClusterInfo(ctx context.Context, in *ClusterInfoRequest, opts ...grpc.CallOption) (*ClusterInfoResponse, error)
	ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error)
	GetDashboardData(ctx context.Context, in *DashboardDataRequest, opts ...grpc.CallOption) (*DashboardDataResponse, error)
}

type forgeSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewForgeSchedulerClient(cc grpc.ClientConnInterface) ForgeSchedulerClient {
	return &forgeSchedulerClient{cc}
}

func (c *forgeSchedulerClient) SubmitTask(ctx context.Context, in *TaskRequest, opts ...grpc.CallOption) (*TaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResponse)
	err := c.cc.Invoke(ctx, ForgeScheduler_SubmitTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeSchedulerClient) GetTaskStatus(ctx context.Context, in *TaskStatusRequest, opts ...grpc.CallOption) (*TaskStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskStatusResponse)
	err := c.cc.Invoke(ctx, ForgeScheduler_GetTaskStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeSchedulerClient) RegisterWorker(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[WorkerHeartbeat, TaskAssignment], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ForgeScheduler_ServiceDesc.Streams[0], ForgeScheduler_RegisterWorker_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WorkerHeartbeat, TaskAssignment]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForgeScheduler_RegisterWorkerClient = grpc.BidiStreamingClient[WorkerHeartbeat, TaskAssignment]

func (c *forgeSchedulerClient) ReportTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*TaskResultAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskResultAck)
	err := c.cc.Invoke(ctx, ForgeScheduler_ReportTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeSchedulerClient) WatchTask(ctx context.Context, in *WatchTaskRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[TaskStatusResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ForgeScheduler_ServiceDesc.Streams[1], ForgeScheduler_WatchTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchTaskRequest, TaskStatusResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForgeScheduler_WatchTaskClient = grpc.ServerStreamingClient[TaskStatusResponse]

func (c *forgeSchedulerClient) GetClusterInfo(ctx context.Context, in *ClusterInfoRequest, opts ...grpc.CallOption) (*ClusterInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClusterInfoResponse)
	err := c.cc.Invoke(ctx, ForgeScheduler_GetClusterInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeSchedulerClient) ListTasks(ctx context.Context, in *ListTasksRequest, opts ...grpc.CallOption) (*ListTasksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksResponse)
	err := c.cc.Invoke(ctx, ForgeScheduler_ListTasks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *forgeSchedulerClient) GetDashboardData(ctx context.Context, in *DashboardDataRequest, opts ...grpc.CallOption) (*DashboardDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DashboardDataResponse)
	err := c.cc.Invoke(ctx, ForgeScheduler_GetDashboardData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ForgeSchedulerServer is the server API for ForgeScheduler service.
// All implementations must embed UnimplementedForgeSchedulerServer
// for forward compatibility.
type ForgeSchedulerServer interface {
	SubmitTask(context.Context, *TaskRequest) (*TaskResponse, error)
	GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error)
	RegisterWorker(grpc.BidiStreamingServer[WorkerHeartbeat, TaskAssignment]) error
	ReportTaskResult(context.Context, *TaskResult) (*TaskResultAck, error)
	WatchTask(*WatchTaskRequest, grpc.ServerStreamingServer[TaskStatusResponse]) error
	GetClusterInfo(context.Context, *ClusterInfoRequest) (*ClusterInfoResponse, error)
	ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error)
	GetDashboardData(context.Context, *DashboardDataRequest) (*DashboardDataResponse, error)
	mustEmbedUnimplementedForgeSchedulerServer()
}

// UnimplementedForgeSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedForgeSchedulerServer struct{}

func (UnimplementedForgeSchedulerServer) SubmitTask(context.Context, *TaskRequest) (*TaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitTask not implemented")
}
func (UnimplementedForgeSchedulerServer) GetTaskStatus(context.Context, *TaskStatusRequest) (*TaskStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaskStatus not implemented")
}
func (UnimplementedForgeSchedulerServer) RegisterWorker(grpc.BidiStreamingServer[WorkerHeartbeat, TaskAssignment]) error {
	return status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedForgeSchedulerServer) ReportTaskResult(context.Context, *TaskResult) (*TaskResultAck, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTaskResult not implemented")
}
func (UnimplementedForgeSchedulerServer) WatchTask(*WatchTaskRequest, grpc.ServerStreamingServer[TaskStatusResponse]) error {
	return status.Error(codes.Unimplemented, "method WatchTask not implemented")
}
func (UnimplementedForgeSchedulerServer) GetClusterInfo(context.Context, *ClusterInfoRequest) (*ClusterInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterInfo not implemented")
}
func (UnimplementedForgeSchedulerServer) ListTasks(context.Context, *ListTasksRequest) (*ListTasksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTasks not implemented")
}
func (UnimplementedForgeSchedulerServer) GetDashboardData(context.Context, *DashboardDataRequest) (*DashboardDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDashboardData not implemented")
}
func (UnimplementedForgeSchedulerServer) mustEmbedUnimplementedForgeSchedulerServer() {}
func (UnimplementedForgeSchedulerServer) testEmbeddedByValue()                        {}

// UnsafeForgeSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ForgeSchedulerServer will
// result in compilation errors.
type UnsafeForgeSchedulerServer interface {
	mustEmbedUnimplementedForgeSchedulerServer()
}

func RegisterForgeSchedulerServer(s grpc.ServiceRegistrar, srv ForgeSchedulerServer) {
	// If the following call panics, it indicates UnimplementedForgeSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ForgeScheduler_ServiceDesc, srv)
}

func _ForgeScheduler_SubmitTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeSchedulerServer).SubmitTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeScheduler_SubmitTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeSchedulerServer).SubmitTask(ctx, req.(*TaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeScheduler_GetTaskStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeSchedulerServer).GetTaskStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeScheduler_GetTaskStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeSchedulerServer).GetTaskStatus(ctx, req.(*TaskStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeScheduler_RegisterWorker_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ForgeSchedulerServer).RegisterWorker(&grpc.GenericServerStream[WorkerHeartbeat, TaskAssignment]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForgeScheduler_RegisterWorkerServer = grpc.BidiStreamingServer[WorkerHeartbeat, TaskAssignment]

func _ForgeScheduler_ReportTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeSchedulerServer).ReportTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeScheduler_ReportTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeSchedulerServer).ReportTaskResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeScheduler_WatchTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchTaskRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ForgeSchedulerServer).WatchTask(m, &grpc.GenericServerStream[WatchTaskRequest, TaskStatusResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ForgeScheduler_WatchTaskServer = grpc.ServerStreamingServer[TaskStatusResponse]

func _ForgeScheduler_GetClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeSchedulerServer).GetClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeScheduler_GetClusterInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeSchedulerServer).GetClusterInfo(ctx, req.(*ClusterInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeScheduler_ListTasks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeSchedulerServer).ListTasks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeScheduler_ListTasks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeSchedulerServer).ListTasks(ctx, req.(*ListTasksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ForgeScheduler_GetDashboardData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DashboardDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ForgeSchedulerServer).GetDashboardData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ForgeScheduler_GetDashboardData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ForgeSchedulerServer).GetDashboardData(ctx, req.(*DashboardDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ForgeScheduler_ServiceDesc is the grpc.ServiceDesc for ForgeScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ForgeScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "forge.ForgeScheduler",
	HandlerType: (*ForgeSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SubmitTask",
			Handler:    _ForgeScheduler_SubmitTask_Handler,
		},
		{
			MethodName: "GetTaskStatus",
			Handler:    _ForgeScheduler_GetTaskStatus_Handler,
		},
		{
			MethodName: "ReportTaskResult",
			Handler:    _ForgeScheduler_ReportTaskResult_Handler,
		},
		{
			MethodName: "GetClusterInfo",
			Handler:    _ForgeScheduler_GetClusterInfo_Handler,
		},
		{
			MethodName: "ListTasks",
			Handler:    _ForgeScheduler_ListTasks_Handler,
		},
		{
			MethodName: "GetDashboardData",
			Handler:    _ForgeScheduler_GetDashboardData_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "RegisterWorker",
			Handler:       _ForgeScheduler_RegisterWorker_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "WatchTask",
			Handler:       _ForgeScheduler_WatchTask_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "internal/proto/forgepb/forge.proto",
}
